// Flujos de conversación tipo ManyChat: cajitas (nodos) conectadas por puntos.
// Cada flujo = cómo se estructura una conversación (disparador → mensajes → ramas).
// ANOVA = IA automática del proyecto (nodos kind "ai"): clasifica, responde
// dinámico en voz de Lana, escala a humano y aprende. 20 flujos.
// REGLA DE COSTO: nodos "message" = respuestas PREDEFINIDAS (instantáneas, SIN
// tokens) para reacciones/comentarios/saludos; nodos "ai" (ANOVA) = respuesta
// con IA (Claude), solo cuando hace falta una respuesta humana real.

export type FlowKind = "trigger" | "message" | "choice" | "action" | "handoff" | "ai";

export interface FlowNode {
  id: string;
  kind: FlowKind;
  x: number;
  y: number;
  title?: string;
  text?: string;
  options?: string[];
}

export interface FlowEdge {
  from: string;
  to: string;
  fromOption?: number; // índice de la opción (botón) del nodo choice
  label?: string;
}

export interface FlowDef {
  id: string;
  code: string;
  name: string;
  desc: string;
  channel: "whatsapp" | "instagram" | "facebook" | "all";
  nodes: FlowNode[];
  edges: FlowEdge[];
}

const X = [40, 360, 700, 1040, 1380, 1720]; // columnas

export const FLOWS: FlowDef[] = [
  {
    id: "f1",
    code: "F1",
    name: "Bienvenida · Primer Contacto",
    desc: "ANOVA clasifica el primer mensaje y enruta a cotizar, asesorar o precio.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 160, title: "Disparador", text: "hola · buenas · info · precio · tatu 👋" },
      { id: "ai1", kind: "ai", x: X[1], y: 160, title: "ANOVA · Intención", text: "Clasifica el 1er mensaje (saludo/idea/precio/ubicación/reclamo) y enruta." },
      { id: "m1", kind: "message", x: X[2], y: 160, title: "Saludo Lana", text: "Hola, qué gusto saludarte 🖤 Soy Lana, de LAST RULES — El Templo de la Piel. ¿Qué Pieza sueñas y en qué zona la imaginas? ✨" },
      { id: "c1", kind: "choice", x: X[3], y: 150, title: "¿Cómo viene?", options: ["Ya sé qué quiero", "Idea vaga", "¿Cuánto cuesta?", "Ubicación / horario"] },
      { id: "h1", kind: "handoff", x: X[4], y: 20, title: "→ F2 Cotización", text: "Recoge idea/zona/tamaño." },
      { id: "h2", kind: "handoff", x: X[4], y: 150, title: "→ F3 Asesoría", text: "Orienta o agenda asesoría." },
      { id: "h3", kind: "handoff", x: X[4], y: 280, title: "→ F7 Precio", text: "Maneja la objeción de valor." },
      { id: "m2", kind: "message", x: X[4], y: 410, title: "Ubicación / horario", text: "El Templo · Bogotá 📍 Mar–Sáb 11am–8pm. ¿Te muestro portafolio o agendamos? 👑" },
      { id: "ai2", kind: "ai", x: X[3], y: 400, title: "ANOVA · Fallback", text: "Si nada encaja, responde como Lana y reencauza a agendar." },
    ],
    edges: [
      { from: "t", to: "ai1" },
      { from: "ai1", to: "m1" },
      { from: "ai1", to: "ai2", label: "no encaja" },
      { from: "m1", to: "c1" },
      { from: "c1", to: "h1", fromOption: 0 },
      { from: "c1", to: "h2", fromOption: 1 },
      { from: "c1", to: "h3", fromOption: 2 },
      { from: "c1", to: "m2", fromOption: 3 },
    ],
  },
  {
    id: "f2",
    code: "F2",
    name: "Cotización",
    desc: "Captura idea/zona/tamaño, ANOVA lee la referencia, empuja a abono.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "quiero cotizar · describe su idea" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Pide detalles", text: "Cuéntame estilo, tamaño aprox (cm) y zona. Si tienes referencia, mándala 🖤" },
      { id: "ai1", kind: "ai", x: X[2], y: 60, title: "ANOVA · Lee referencia", text: "Interpreta texto/imagen, estima complejidad y resume idea/zona/tamaño." },
      { id: "a1", kind: "action", x: X[3], y: 60, title: "Guarda en CRM", text: "estado = Cotizado · idea/zona/tamaño/ref" },
      { id: "m2", kind: "message", x: X[2], y: 220, title: "Rango honesto", text: "Por lo que describes, los Maestros lo cotizan a la medida 👑 No damos precio en frío para no quedarnos cortos con tu Obra." },
      { id: "m3", kind: "message", x: X[3], y: 220, title: "Cierre a agenda", text: "Para apartar cupo va un abono de $100.000 que se descuenta del total. ¿Entre semana o fin de semana?" },
      { id: "c1", kind: "choice", x: X[4], y: 220, title: "Disponibilidad", options: ["Entre semana", "Fin de semana", "Aún lo pienso"] },
      { id: "h1", kind: "handoff", x: X[5], y: 120, title: "→ F5 Agendamiento", text: "" },
      { id: "h2", kind: "handoff", x: X[5], y: 320, title: "→ F8 Seguimiento", text: "Nutre y reactiva." },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "ai1" },
      { from: "ai1", to: "a1" },
      { from: "m1", to: "m2" },
      { from: "m2", to: "m3" },
      { from: "m3", to: "c1" },
      { from: "c1", to: "h1", fromOption: 0 },
      { from: "c1", to: "h1", fromOption: 1 },
      { from: "c1", to: "h2", fromOption: 2 },
    ],
  },
  {
    id: "f3",
    code: "F3",
    name: "Sin idea clara · Asesoría",
    desc: "ANOVA sugiere estilos/zonas u ofrece asesoría presencial gratis.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "no sé qué · algo bonito · ayúdame" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Normaliza", text: "Para eso somos perfectos 🖤 ¿Lo imaginas visible o íntimo? ¿Te llama lo minimalista o algo con presencia? ✨" },
      { id: "ai1", kind: "ai", x: X[2], y: 180, title: "ANOVA · Sugiere estilo", text: "Según respuestas y tendencias propone 2–3 estilos y zonas que favorecen." },
      { id: "c1", kind: "choice", x: X[3], y: 180, title: "Camino", options: ["Muéstrame estilos", "Asesoría presencial", "Tengo dudas sueltas"] },
      { id: "m2", kind: "message", x: X[4], y: 60, title: "Estilos sugeridos", text: "Línea fina, dark work o neo-tribal te quedarían divinos. Te paso ejemplos del portafolio 👑" },
      { id: "h1", kind: "handoff", x: X[4], y: 200, title: "→ F5 (asesoría gratis)", text: "" },
      { id: "ai2", kind: "ai", x: X[4], y: 340, title: "ANOVA · Resuelve dudas", text: "Responde dudas abiertas en voz de Lana y cierra invitando a agendar." },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "m2", fromOption: 0 },
      { from: "c1", to: "h1", fromOption: 1 },
      { from: "c1", to: "ai2", fromOption: 2 },
      { from: "m2", to: "h1" },
    ],
  },
  {
    id: "f4",
    code: "F4",
    name: "Proceso y Cuidados",
    desc: "FAQ: dolor, cuidados, freehand, duración; ANOVA cubre lo demás.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 210, title: "Disparador", text: "duele · cuidados · freehand · cuánto dura · sangra" },
      { id: "c1", kind: "choice", x: X[1], y: 210, title: "¿Qué pregunta?", options: ["Dolor", "Cuidados", "Freehand", "Duración"] },
      { id: "m1", kind: "message", x: X[2], y: 30, title: "Dolor", text: "Se siente, pero es llevable; antebrazo/muslo son de los más amables 🖤" },
      { id: "m2", kind: "message", x: X[2], y: 150, title: "Cuidados", text: "Jabón neutro 2x/día, crema sin fragancia, nada de sol/piscina ~4 semanas 🤍" },
      { id: "m3", kind: "message", x: X[2], y: 270, title: "Freehand", text: "Se dibuja a mano alzada sobre tu piel; solo se tatúa cuando apruebas el trazo ✨" },
      { id: "m4", kind: "message", x: X[2], y: 390, title: "Duración", text: "Depende del tamaño y detalle; en la asesoría te damos el tiempo exacto 👑" },
      { id: "ai1", kind: "ai", x: X[3], y: 380, title: "ANOVA · Otra duda", text: "Cualquier pregunta fuera de lista la responde ANOVA con la info del estudio." },
      { id: "m5", kind: "message", x: X[4], y: 210, title: "Reencauza", text: "¿Te ayudo a agendar tu Pieza o tu asesoría? 🖤" },
      { id: "h1", kind: "handoff", x: X[5], y: 210, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "t", to: "ai1", label: "fuera de lista" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "c1", to: "m4", fromOption: 3 },
      { from: "m1", to: "m5" },
      { from: "m2", to: "m5" },
      { from: "m3", to: "m5" },
      { from: "m4", to: "m5" },
      { from: "ai1", to: "m5" },
      { from: "m5", to: "h1" },
    ],
  },
  {
    id: "f5",
    code: "F5",
    name: "Agendamiento y Abono",
    desc: "Tipo de cita → abono → evento en Calendar → recordatorios ANOVA.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 200, title: "Disparador", text: "agendar · cita · abono · reservar" },
      { id: "c1", kind: "choice", x: X[1], y: 200, title: "Tipo de cita", options: ["Asesoría gratis", "Sesión (con abono)"] },
      { id: "m1", kind: "message", x: X[2], y: 80, title: "Confirma asesoría", text: "¡Genial! Te espero en El Templo. Trae tus referencias 🤍 ¿Qué día te queda mejor?" },
      { id: "m2", kind: "message", x: X[2], y: 280, title: "Datos de abono", text: "Abono $100.000 (se descuenta). Nequi/Daviplata 3227062595 — LAST RULES. Mándame el comprobante 🖤" },
      { id: "a1", kind: "action", x: X[3], y: 200, title: "Crea evento", text: "Google Calendar (Maestro) + estado = Agendando" },
      { id: "a2", kind: "action", x: X[3], y: 360, title: "Notifica al Maestro", text: "Push/WhatsApp interno al tatuador asignado." },
      { id: "ai1", kind: "ai", x: X[4], y: 200, title: "ANOVA · Recordatorios", text: "Programa recordatorio 24h y 2h antes; confirma o reagenda automático." },
      { id: "m3", kind: "message", x: X[5], y: 200, title: "Confirmación", text: "¡Listo! Quedó tu cupo 👑 Te llega recordatorio. Cualquier cambio, escríbeme." },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "m1", to: "a1" },
      { from: "m2", to: "a1" },
      { from: "a1", to: "a2" },
      { from: "a1", to: "ai1" },
      { from: "ai1", to: "m3" },
    ],
  },
  {
    id: "f6",
    code: "F6",
    name: "Exterior / Giras",
    desc: "ANOVA detecta ciudad/país y propone viaje a Bogotá o lista de gira.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "otra ciudad · exterior · USA · vienen a" },
      { id: "ai1", kind: "ai", x: X[1], y: 180, title: "ANOVA · Geo", text: "Detecta ciudad/país y propone viaje a Bogotá o lista de gira." },
      { id: "c1", kind: "choice", x: X[2], y: 180, title: "¿Cómo prefiere?", options: ["Viajo a Bogotá", "Que vengan (gira)"] },
      { id: "m1", kind: "message", x: X[3], y: 70, title: "Viaje", text: "Agrupamos varios días para tu Pieza. Agendemos con anticipación 👑" },
      { id: "m2", kind: "message", x: X[3], y: 290, title: "Gira", text: "Te dejo en la lista prioritaria de tu ciudad; coordina el director artístico 🖤" },
      { id: "a1", kind: "action", x: X[4], y: 290, title: "Lista de gira", text: "Guarda ciudad + interés para convocar gira." },
      { id: "h1", kind: "handoff", x: X[4], y: 70, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "m1", to: "h1" },
      { from: "m2", to: "a1" },
    ],
  },
  {
    id: "f7",
    code: "F7",
    name: "Objeción de Precio",
    desc: "Valida, explica valor, ANOVA reencuadra; NUNCA descuenta.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "caro · descuento · rebaja · barato" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Valida + valor", text: "Te entiendo 🤍 Es arte de autor a mano alzada hecho para tu anatomía; por eso no hay descuentos. Pero ajustamos alcance a tu presupuesto." },
      { id: "ai1", kind: "ai", x: X[2], y: 180, title: "ANOVA · Reencuadre", text: "Detecta presupuesto y propone tamaño/zona/etapas sin tocar el precio." },
      { id: "c1", kind: "choice", x: X[3], y: 180, title: "Respuesta", options: ["Ajustar tamaño", "Hacerlo por etapas", "Insiste en descuento"] },
      { id: "m2", kind: "message", x: X[4], y: 50, title: "Ajuste", text: "Lo llevamos a un tamaño que te cuadre y queda igual de poderoso 👑" },
      { id: "m3", kind: "message", x: X[4], y: 180, title: "Por etapas", text: "Arrancamos una primera etapa y crecemos la Obra por sesiones ✨" },
      { id: "m4", kind: "message", x: X[4], y: 310, title: "Mantén política", text: "El valor sostiene la calidad y la bioseguridad 🖤 Prefiero cuidar tu Pieza antes que el precio." },
      { id: "h1", kind: "handoff", x: X[5], y: 115, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "m2", fromOption: 0 },
      { from: "c1", to: "m3", fromOption: 1 },
      { from: "c1", to: "m4", fromOption: 2 },
      { from: "m2", to: "h1" },
      { from: "m3", to: "h1" },
    ],
  },
  {
    id: "f8",
    code: "F8",
    name: "Seguimiento · Reactivación",
    desc: "Recordatorios, cuidados 48h y ANOVA reactiva inactivos.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 200, title: "Disparador", text: "post-sesión · retoque · cuidado · gracias · recordar" },
      { id: "m1", kind: "message", x: X[1], y: 70, title: "Recordatorio 24h", text: "¡Mañana es tu día! Llega alimentado/a y con la zona hidratada 🖤" },
      { id: "m2", kind: "message", x: X[1], y: 210, title: "Cuidados 48h", text: "Tu Obra quedó increíble ✨ Jabón neutro, crema sin fragancia, sin sol/piscina." },
      { id: "ai1", kind: "ai", x: X[2], y: 350, title: "ANOVA · Reactiva", text: "Detecta clientes inactivos y propone nueva Pieza o retoque en buen momento." },
      { id: "c1", kind: "choice", x: X[3], y: 210, title: "Reactivar", options: ["Quiere otra Pieza", "Retoque", "Solo gracias"] },
      { id: "h1", kind: "handoff", x: X[4], y: 80, title: "→ F2 Cotización", text: "" },
      { id: "m3", kind: "message", x: X[4], y: 220, title: "Retoque", text: "Tu retoque de cortesía está dentro de los 30 días 🤍 ¿Qué día vienes?" },
      { id: "m4", kind: "message", x: X[4], y: 360, title: "Cierre cálido", text: "Gracias por confiar tu piel en LAST RULES 🖤 Aquí estaré para tu próxima Obra." },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "t", to: "m2" },
      { from: "m2", to: "c1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "h1", fromOption: 0 },
      { from: "c1", to: "m3", fromOption: 1 },
      { from: "c1", to: "m4", fromOption: 2 },
    ],
  },
  {
    id: "f9",
    code: "F9",
    name: "Menores de edad",
    desc: "ANOVA verifica edad; solo con acompañamiento legal del acudiente.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "tengo 16 · soy menor · desde qué edad" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Política", text: "Gracias por preguntarlo 🖤 Para tatuar a un menor necesitamos acompañamiento legal del acudiente (presente y con autorización)." },
      { id: "ai1", kind: "ai", x: X[2], y: 180, title: "ANOVA · Verifica edad", text: "Si declara ser menor, bloquea agendamiento directo y exige acudiente." },
      { id: "c1", kind: "choice", x: X[3], y: 180, title: "¿Tiene acudiente?", options: ["Sí, puede acompañarme", "No por ahora"] },
      { id: "h1", kind: "handoff", x: X[4], y: 70, title: "→ director artístico", text: "Coordina con acudiente y documentación." },
      { id: "m2", kind: "message", x: X[4], y: 290, title: "Puerta abierta", text: "Cuando llegue tu momento, aquí estaremos ✨" },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "h1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
    ],
  },
  {
    id: "f10",
    code: "F10",
    name: "Reclamo · Escalar",
    desc: "ANOVA detecta sentimiento, empatiza y escala al director artístico.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "no me gustó · quedó mal · reclamo" },
      { id: "ai1", kind: "ai", x: X[1], y: 180, title: "ANOVA · Sentimiento", text: "Detecta molestia/urgencia y baja la temperatura antes de responder." },
      { id: "m1", kind: "message", x: X[2], y: 180, title: "Empatía", text: "Lamento mucho que no estés satisfecho con tu Pieza 🖤 Quiero que quedes feliz." },
      { id: "c1", kind: "choice", x: X[3], y: 180, title: "Tipo", options: ["Resultado / retoque", "Atención / servicio"] },
      { id: "h1", kind: "handoff", x: X[4], y: 70, title: "→ director artístico", text: "Te conecto con el director artístico; te escribe en breve 🤍" },
      { id: "a1", kind: "action", x: X[4], y: 290, title: "Registra caso", text: "Abre ticket en CRM + notifica al equipo." },
    ],
    edges: [
      { from: "t", to: "ai1" },
      { from: "ai1", to: "m1" },
      { from: "m1", to: "c1" },
      { from: "c1", to: "h1", fromOption: 0 },
      { from: "c1", to: "a1", fromOption: 1 },
    ],
  },
  {
    id: "f11",
    code: "F11",
    name: "Catálogo · Estilos & Portafolio",
    desc: "Muestra estilos, Maestros y portafolio; ANOVA afina por gusto.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 210, title: "Disparador", text: "portafolio · estilos · trabajos · fotos · tatuadores" },
      { id: "ai1", kind: "ai", x: X[1], y: 210, title: "ANOVA · Gusto", text: "Pregunta gusto y muestra el set de fotos/estilos más afín." },
      { id: "c1", kind: "choice", x: X[2], y: 210, title: "¿Qué te late?", options: ["Línea fina", "Dark work", "Neo-tribal", "Ver Maestros"] },
      { id: "m1", kind: "message", x: X[3], y: 40, title: "Línea fina", text: "Trazos delicados y elegantes 🤍 Te paso ejemplos." },
      { id: "m2", kind: "message", x: X[3], y: 150, title: "Dark work", text: "Negros sólidos con presencia 🖤 Mira estas Obras." },
      { id: "m3", kind: "message", x: X[3], y: 260, title: "Neo-tribal", text: "Formas orgánicas con fuerza ✨" },
      { id: "m4", kind: "message", x: X[3], y: 370, title: "Maestros", text: "El Lobo, Aguja Fina, Tinta Negra y Maestra Ámbar — cada uno con su sello 👑" },
      { id: "m5", kind: "message", x: X[4], y: 210, title: "Invita a cotizar", text: "¿Quieres que cotizemos tu versión? 🖤" },
      { id: "h1", kind: "handoff", x: X[5], y: 210, title: "→ F2 Cotización", text: "" },
    ],
    edges: [
      { from: "t", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "c1", to: "m4", fromOption: 3 },
      { from: "m1", to: "m5" },
      { from: "m2", to: "m5" },
      { from: "m3", to: "m5" },
      { from: "m4", to: "m5" },
      { from: "m5", to: "h1" },
    ],
  },
  {
    id: "f12",
    code: "F12",
    name: "ANOVA · Cerebro / Fallback",
    desc: "IA siempre activa: responde lo que ningún flujo cubre, escala y aprende.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 200, title: "Mensaje sin flujo", text: "Cualquier texto que no dispare F1–F11" },
      { id: "ai1", kind: "ai", x: X[1], y: 200, title: "ANOVA · Comprende", text: "Interpreta intención con el contexto del lead y la base de conocimiento." },
      { id: "c1", kind: "choice", x: X[2], y: 200, title: "¿Puede resolver?", options: ["Sí, responde", "Necesita humano", "Es comercial"] },
      { id: "ai2", kind: "ai", x: X[3], y: 60, title: "ANOVA · Responde", text: "Genera respuesta en voz de Lana, sin precio ni descuento, y reencauza." },
      { id: "h1", kind: "handoff", x: X[3], y: 200, title: "→ director artístico", text: "Escala a humano con resumen del caso." },
      { id: "h2", kind: "handoff", x: X[3], y: 340, title: "→ F2 Cotización", text: "Si hay intención de compra, cierra." },
      { id: "a1", kind: "action", x: X[4], y: 60, title: "Aprende", text: "Guarda la pregunta nueva para enriquecer la base." },
    ],
    edges: [
      { from: "t", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "ai2", fromOption: 0 },
      { from: "c1", to: "h1", fromOption: 1 },
      { from: "c1", to: "h2", fromOption: 2 },
      { from: "ai2", to: "a1" },
    ],
  },
  {
    id: "f13",
    code: "F13",
    name: "Comentarios → DM (IG/FB)",
    desc: "Comentario en publicación → responde público + abre DM. Predefinido por palabra clave; ANOVA solo si es charla real.",
    channel: "instagram",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 220, title: "Comentario en post", text: "precio · info · cuánto · link · 🔥 · 😍 · «quiero»" },
      { id: "a1", kind: "action", x: X[1], y: 80, title: "Responder comentario", text: "Respuesta pública corta (predefinida): «¡Te escribo al DM! 🖤»" },
      { id: "a2", kind: "action", x: X[1], y: 240, title: "Abrir DM", text: "Envía mensaje directo al inbox (IG/Messenger)." },
      { id: "c1", kind: "choice", x: X[2], y: 240, title: "Tipo (palabra clave)", options: ["Precio / info", "Solo emoji 🔥😍", "Etiquetó a alguien", "Pregunta compleja"] },
      { id: "m1", kind: "message", x: X[3], y: 60, title: "DM precio · predefinida", text: "Hola 🖤 vi tu comentario. ¿Qué Pieza imaginas y en qué zona? Te asesoro ✨" },
      { id: "m2", kind: "message", x: X[3], y: 190, title: "DM emoji · predefinida", text: "¡Gracias por el 🔥! ¿Quieres ver más Obras o agendamos? 👑" },
      { id: "m3", kind: "message", x: X[3], y: 320, title: "DM etiqueta · predefinida", text: "¡Qué buena! Si tú o tu amig@ quieren su Pieza, aquí estamos 🤍" },
      { id: "ai1", kind: "ai", x: X[3], y: 450, title: "ANOVA · DM (IA)", text: "Pregunta compleja → responde humano vía Claude y reencauza a agendar." },
      { id: "h1", kind: "handoff", x: X[4], y: 190, title: "→ F1 Bienvenida", text: "" },
    ],
    edges: [
      { from: "t", to: "a1" },
      { from: "t", to: "a2" },
      { from: "a2", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "c1", to: "ai1", fromOption: 3 },
      { from: "m1", to: "h1" },
      { from: "m2", to: "h1" },
      { from: "m3", to: "h1" },
      { from: "ai1", to: "h1" },
    ],
  },
  {
    id: "f14",
    code: "F14",
    name: "Reacciones a Historias",
    desc: "Reacción o respuesta a historia → mensaje predefinido según reacción. SIN IA (no consume tokens).",
    channel: "instagram",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 220, title: "Reacción a historia", text: "❤️ 🔥 😍 😮 👏 o respuesta a la story" },
      { id: "c1", kind: "choice", x: X[1], y: 220, title: "Tipo de reacción", options: ["❤️ / 😍 amor", "🔥 fuego", "😮 / 👏 asombro", "Respondió con texto"] },
      { id: "m1", kind: "message", x: X[2], y: 60, title: "Predefinida · amor", text: "¡Gracias por el amor! 🤍 ¿Te muestro disponibilidad para tu Pieza? 👑" },
      { id: "m2", kind: "message", x: X[2], y: 190, title: "Predefinida · fuego", text: "¡Ese fuego nos encanta! 🔥 ¿Quieres cotizar tu idea? 🖤" },
      { id: "m3", kind: "message", x: X[2], y: 320, title: "Predefinida · asombro", text: "¡Gracias! 👑 Dime qué zona del cuerpo y arrancamos ✨" },
      { id: "ai1", kind: "ai", x: X[2], y: 450, title: "ANOVA (IA)", text: "Solo si respondió con texto real: responde humano y enruta a F1." },
      { id: "h1", kind: "handoff", x: X[3], y: 220, title: "→ F1 Bienvenida", text: "" },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "c1", to: "ai1", fromOption: 3 },
      { from: "m1", to: "h1" },
      { from: "m2", to: "h1" },
      { from: "m3", to: "h1" },
      { from: "ai1", to: "h1" },
    ],
  },
  {
    id: "f15",
    code: "F15",
    name: "Reacciones rápidas / Mensajes cortos",
    desc: "Sticker, 👍, «hola», «?», nota de voz → respuesta predefinida instantánea. IA solo para audio.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 220, title: "Reacción / mensaje corto", text: "👍 · sticker · «hola» · «?» · nota de voz" },
      { id: "c1", kind: "choice", x: X[1], y: 220, title: "Tipo", options: ["Saludo simple", "👍 / sticker", "Solo «?»", "Nota de voz"] },
      { id: "m1", kind: "message", x: X[2], y: 60, title: "Predefinida · saludo", text: "¡Hola! 🖤 Soy Lana de LAST RULES. ¿Qué Pieza tienes en mente?" },
      { id: "m2", kind: "message", x: X[2], y: 190, title: "Predefinida · sticker", text: "🤍 ¿Te ayudo a cotizar o a agendar tu Pieza?" },
      { id: "m3", kind: "message", x: X[2], y: 320, title: "Predefinida · «?»", text: "Cuéntame un poco más y te oriento al toque ✨" },
      { id: "a1", kind: "action", x: X[2], y: 450, title: "Transcribe audio", text: "ANOVA transcribe la nota de voz (solo si hay audio)." },
      { id: "ai1", kind: "ai", x: X[3], y: 450, title: "ANOVA (IA)", text: "Interpreta el audio transcrito y responde humano." },
      { id: "h1", kind: "handoff", x: X[3], y: 180, title: "→ F1 Bienvenida", text: "" },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "c1", to: "a1", fromOption: 3 },
      { from: "a1", to: "ai1" },
      { from: "m1", to: "h1" },
      { from: "m2", to: "h1" },
      { from: "m3", to: "h1" },
      { from: "ai1", to: "h1" },
    ],
  },
  {
    id: "f16",
    code: "F16",
    name: "Cover-up / Retrabajo",
    desc: "Tapar o mejorar un tatuaje viejo: pide foto, ANOVA evalúa viabilidad, enruta a asesoría.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "cover · tapar · cubrir · arreglar · tatuaje viejo" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Pide foto", text: "Claro que sí 🖤 Mándame una foto clara del tatuaje actual y la zona ✨" },
      { id: "ai1", kind: "ai", x: X[2], y: 180, title: "ANOVA · Evalúa", text: "Lee la foto, estima si se cubre o necesita aclarado/láser previo y propone estilo." },
      { id: "c1", kind: "choice", x: X[3], y: 180, title: "Viabilidad", options: ["Se puede cubrir", "Necesita aclarado/láser"] },
      { id: "m2", kind: "message", x: X[4], y: 80, title: "Cover viable", text: "¡Buenas noticias! Se puede transformar en una Obra nueva 👑 Agendemos asesoría." },
      { id: "m3", kind: "message", x: X[4], y: 280, title: "Requiere láser", text: "Para que quede impecable conviene aclararlo antes 🤍 Te explico el proceso en asesoría." },
      { id: "h1", kind: "handoff", x: X[5], y: 180, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "ai1" },
      { from: "ai1", to: "c1" },
      { from: "c1", to: "m2", fromOption: 0 },
      { from: "c1", to: "m3", fromOption: 1 },
      { from: "m2", to: "h1" },
      { from: "m3", to: "h1" },
    ],
  },
  {
    id: "f17",
    code: "F17",
    name: "Referidos / Recomendados",
    desc: "Cliente recomendado o que trae a un amigo; reconoce el vínculo y agenda. Sin descuento.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "me recomendaron · vengo de parte de · mi amig@ se tatuó" },
      { id: "c1", kind: "choice", x: X[1], y: 180, title: "¿Quién?", options: ["Me recomendó alguien", "Quiero traer a un amig@"] },
      { id: "m1", kind: "message", x: X[2], y: 80, title: "Recomendado", text: "¡Qué honor que te enviaran a El Templo! 🖤 ¿Qué Pieza imaginas?" },
      { id: "m2", kind: "message", x: X[2], y: 280, title: "Trae amig@", text: "¡Vengan en dúo! 👑 Coordinamos sesiones seguidas para los dos 🤍" },
      { id: "a1", kind: "action", x: X[3], y: 280, title: "Registra referido", text: "Marca origen = referido en el CRM." },
      { id: "h1", kind: "handoff", x: X[3], y: 80, title: "→ F2 Cotización", text: "" },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "m1", to: "h1" },
      { from: "m2", to: "a1" },
    ],
  },
  {
    id: "f18",
    code: "F18",
    name: "Reseñas / Testimonios",
    desc: "Post-sesión: pide reseña en Google/IG y guarda testimonio. Predefinido (sin tokens).",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador (post-sesión)", text: "Tras marcar la sesión como completada" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Pide reseña · predefinida", text: "¡Fue un gusto crear tu Obra! 🖤 ¿Nos regalas una reseña? Te dejo el link de Google ✨" },
      { id: "c1", kind: "choice", x: X[2], y: 180, title: "¿Reseñó?", options: ["Sí, dejé reseña", "Quizá luego"] },
      { id: "m2", kind: "message", x: X[3], y: 80, title: "Agradece · predefinida", text: "¡Mil gracias! 👑 Eso ayuda muchísimo al estudio 🤍" },
      { id: "a1", kind: "action", x: X[3], y: 280, title: "Recordatorio suave", text: "Reprograma un recordatorio amable a los 3 días." },
      { id: "a2", kind: "action", x: X[4], y: 80, title: "Guarda testimonio", text: "Si dejó texto, guárdalo para mostrarlo en la web (panel)." },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "c1" },
      { from: "c1", to: "m2", fromOption: 0 },
      { from: "c1", to: "a1", fromOption: 1 },
      { from: "m2", to: "a2" },
    ],
  },
  {
    id: "f19",
    code: "F19",
    name: "Flash Day / Promos",
    desc: "Diseños flash y fechas especiales (valor agregado, NUNCA descuento).",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "flash · promo · oferta · día especial · combo" },
      { id: "m1", kind: "message", x: X[1], y: 180, title: "Explica flash", text: "Tenemos diseños Flash listos a precio cerrado para fechas especiales 🖤 (cupos limitados)." },
      { id: "c1", kind: "choice", x: X[2], y: 180, title: "Interés", options: ["Ver diseños flash", "¿Hay descuento?"] },
      { id: "m2", kind: "message", x: X[3], y: 80, title: "Muestra flash", text: "Te paso el catálogo Flash del mes ✨ Elige y aparta con abono 👑" },
      { id: "m3", kind: "message", x: X[3], y: 280, title: "Sin descuento", text: "No manejamos descuentos 🤍 pero en Flash Day el valor ya está pensado para ti, con el mismo arte de autor." },
      { id: "h1", kind: "handoff", x: X[4], y: 80, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "m1" },
      { from: "m1", to: "c1" },
      { from: "c1", to: "m2", fromOption: 0 },
      { from: "c1", to: "m3", fromOption: 1 },
      { from: "m2", to: "h1" },
      { from: "m3", to: "m2" },
    ],
  },
  {
    id: "f20",
    code: "F20",
    name: "Piercing & Otros Servicios",
    desc: "Body piercing y joyería (titanio/oro): info, cuidados y agenda.",
    channel: "all",
    nodes: [
      { id: "t", kind: "trigger", x: X[0], y: 180, title: "Disparador", text: "piercing · perforación · joya · titanio · oro" },
      { id: "c1", kind: "choice", x: X[1], y: 180, title: "¿Qué necesita?", options: ["Tipo de piercing", "Material / joyería", "Cuidados"] },
      { id: "m1", kind: "message", x: X[2], y: 60, title: "Tipos", text: "Hacemos oreja, nariz, cuerpo y más, con técnica estéril 🖤 ¿Cuál te llama?" },
      { id: "m2", kind: "message", x: X[2], y: 190, title: "Joyería", text: "Trabajamos titanio implant-grade y oro 👑 hipoalergénico y elegante ✨" },
      { id: "m3", kind: "message", x: X[2], y: 320, title: "Cuidados", text: "Suero fisiológico 2x/día, no girar la joya, evitar piscina las primeras semanas 🤍" },
      { id: "ai1", kind: "ai", x: X[3], y: 320, title: "ANOVA · Dudas", text: "Resuelve dudas específicas de piercing y reencauza a agendar." },
      { id: "h1", kind: "handoff", x: X[3], y: 120, title: "→ F5 Agendamiento", text: "" },
    ],
    edges: [
      { from: "t", to: "c1" },
      { from: "c1", to: "m1", fromOption: 0 },
      { from: "c1", to: "m2", fromOption: 1 },
      { from: "c1", to: "m3", fromOption: 2 },
      { from: "m1", to: "h1" },
      { from: "m2", to: "h1" },
      { from: "m3", to: "ai1" },
      { from: "ai1", to: "h1" },
    ],
  },
];
