import type { Conversation, Channel, Stage, Message, Sender } from "./types";

// Helper: timestamp a N minutos en el pasado
const base = Date.now();
const mins = (m: number) => new Date(base - m * 60000).toISOString();

let mid = 0;
function thread(items: [Sender, string, number][]): Message[] {
  return items.map(([sender, text, m]) => ({
    id: `m${++mid}`,
    sender,
    text,
    at: mins(m),
  }));
}

interface Seed {
  id: string;
  name: string;
  channel: Channel;
  handle?: string;
  phone?: string;
  city?: string;
  lang?: "es" | "en" | "de";
  stage: Stage;
  idea?: string;
  zona?: string;
  tamano?: string;
  tags: string[];
  outcome?: Conversation["outcome"];
  hue: number;
  msgs: [Sender, string, number][];
}

const seeds: Seed[] = [
  {
    id: "c1",
    name: "Mateo Rincón",
    channel: "whatsapp",
    phone: "+57 311 555 2210",
    city: "Bogotá",
    stage: "cerrado",
    idea: "León dark work",
    zona: "Antebrazo",
    tamano: "~15 cm",
    tags: ["tiene_idea", "abono_recibido", "cita_confirmada"],
    outcome: "cerrado",
    hue: 28,
    msgs: [
      ["coleccionista", "Hola, vi su Instagram. Quiero un león en el antebrazo", 240],
      ["lana", "Hola, qué gusto saludarte 🖤 Un león en dark work en el antebrazo queda imponente. ¿De qué tamaño lo imaginas y tienes alguna referencia? ✨", 239],
      ["coleccionista", "Como de 15 cm, en sombras. Sin tatuajes ahí todavía", 238],
      ["lana", "Perfecto: león dark work, antebrazo, ~15 cm 🖤 Lo paso a los tatuadores para tu diseño único hecho para ti a la medida. Para asegurar tu cupo trabajamos con un abono de $100.000 que se descuenta del total. ¿Te queda mejor entre semana o el fin de semana? 👑", 236],
      ["coleccionista", "Fin de semana mejor", 233],
      ["lana", "Genial ✨ Te paso con el agendamiento para apartar tu sábado antes de que se llene la agenda de los tatuadores 🖤", 232],
      ["coleccionista", "Listo ya hice el abono, ahí les mando el comprobante", 60],
      ["lana", "¡Recibido! 🖤 Tu cupo quedó asegurado. Te esperamos en el estudio 👑", 58],
    ],
  },
  {
    id: "c2",
    name: "valentina_mora",
    channel: "instagram",
    handle: "@valentina_mora",
    city: "Bogotá",
    stage: "calificando",
    idea: "Flores finas",
    zona: "Brazo",
    tags: ["tiene_idea", "pregunto_precio"],
    outcome: "seguimiento",
    hue: 320,
    msgs: [
      ["coleccionista", "holaa cuanto vale un tatuaje de flores en el brazo?", 95],
      ["lana", "Hola, qué gusto saludarte 🤍 El valor de el tatuaje depende del diseño, zona, tamaño y complejidad, por eso lo cotiza un tatuador a tu medida. Cuéntame: ¿línea fina o con sombras, y qué tan grande la imaginas? ✨", 94],
      ["coleccionista", "linea fina, algo delicado, del codo hacia abajo", 90],
      ["lana", "Hermoso 🖤 Eso luce elegante en línea fina. Te propongo algo: agenda una asesoría gratis en el estudio y aterrizamos tu diseño único hecho para ti sin compromiso. ¿Te sirve esta semana o la próxima? 👑", 88],
    ],
  },
  {
    id: "c3",
    name: "Andrés Gómez",
    channel: "whatsapp",
    phone: "+57 320 411 8890",
    city: "Medellín",
    stage: "nuevo",
    tags: ["otra_ciudad"],
    idea: "Manga completa",
    outcome: "seguimiento",
    hue: 210,
    msgs: [
      ["coleccionista", "buenas, estoy en medellin, ustedes hacen mangas completas?", 50],
      ["lana", "Buenas, qué gusto 🖤 Claro, las mangas son de nuestras tatuajes favoritas. Atendemos clientes de toda Colombia. ¿Prefieres viajar a Bogotá para tu sesión o que te contemos de nuestras giras? ✨", 49],
      ["coleccionista", "viajaria a bogota, pero quiero ver como seria primero", 47],
      ["lana", "Perfecto 👑 Agendemos una asesoría (puede ser por videollamada) para diseñar tu manga y planear los días. Así aprovechas el viaje al máximo. ¿Qué día te queda bien? 🖤", 45],
    ],
  },
  {
    id: "c4",
    name: "Laura Tatis",
    channel: "facebook",
    city: "Bogotá",
    stage: "cotizado",
    idea: "Retrato de su abuela",
    zona: "Espalda alta",
    tamano: "~20 cm",
    tags: ["tiene_idea", "cotizado"],
    outcome: "agendado",
    hue: 12,
    msgs: [
      ["coleccionista", "Quiero un retrato de mi abuela en la espalda, es muy importante para mí", 180],
      ["lana", "Qué bonito homenaje 🤍 Un retrato pide manos de tatuador y se hace a mano alzada para que quede único. ¿Tienes una foto de buena luz que podamos usar de referencia? 🖤", 179],
      ["coleccionista", "sí tengo varias", 176],
      ["lana", "Perfecto ✨ los tatuadores revisaron y es un proyecto precioso de una sesión larga. Para apartar tu cupo va el abono de $100.000 que se descuenta. ¿Agendamos para esta quincena antes de que se llene? 👑", 120],
      ["coleccionista", "listo agendemos", 90],
    ],
  },
  {
    id: "c5",
    name: "juanpa.ink",
    channel: "instagram",
    handle: "@juanpa.ink",
    city: "Bogotá",
    stage: "agendando",
    idea: "Neo-tribal pecho",
    zona: "Pecho",
    tags: ["tiene_idea", "objecion_precio"],
    outcome: "seguimiento",
    hue: 280,
    msgs: [
      ["coleccionista", "uff y eso esta caro, no hacen descuento?", 70],
      ["lana", "Entiendo 🤍 En LAST RULES cada tatuaje es un Diseño de Autor a mano alzada hecho para tu anatomía, no una plantilla — por eso no manejamos descuentos. Pero podemos ajustar el tamaño o la zona a tu presupuesto. ¿Cuánto tenías pensado invertir? 🖤", 69],
      ["coleccionista", "pues algo razonable, el pecho completo", 66],
      ["lana", "Te propongo arrancar por una primera etapa potente y crecer el tatuaje por sesiones — así cuidas el bolsillo y el resultado 👑 ¿Agendamos una asesoría gratis para definirlo? ✨", 64],
    ],
  },
  {
    id: "c6",
    name: "Sara Delgado",
    channel: "whatsapp",
    phone: "+57 315 220 7741",
    city: "Bogotá",
    stage: "asesoria",
    tags: ["sin_idea", "asesoria_confirmada"],
    outcome: "agendado",
    hue: 160,
    msgs: [
      ["coleccionista", "hola quiero tatuarme algo pero no sé qué", 200],
      ["lana", "Hola, qué rico ese momento 🖤 Para eso somos perfectos. ¿Lo imaginas más visible (brazo, pierna) o íntimo (costado, espalda)? Y dime: ¿te llama lo minimalista o algo con más presencia? ✨", 199],
      ["coleccionista", "algo elegante pero no muy grande, visible", 197],
      ["lana", "Línea fina o un detalle dark work pequeño te quedarían divinos 👑 Lo mejor: agenda una asesoría gratis y entre todos aterrizamos tu diseño único hecho para ti en persona. ¿Jueves o sábado? 🖤", 195],
      ["coleccionista", "sábado", 193],
      ["lana", "¡Listo! Te espero el sábado en el estudio ✨ Trae cualquier referencia que te guste, aunque sea suelta 🤍", 192],
    ],
  },
  {
    id: "c7",
    name: "mariana.rios",
    channel: "instagram",
    handle: "@mariana.rios",
    city: "Cali",
    stage: "nuevo",
    tags: ["otra_ciudad", "interes_gira"],
    outcome: "seguimiento",
    hue: 45,
    msgs: [
      ["coleccionista", "vienen a cali? me encanta su trabajo", 33],
      ["lana", "¡Gracias, qué honor! 🖤 Hacemos giras según la agenda de viajes y la demanda en cada ciudad. En Cali estamos sumando clientes interesados. ¿Quieres que te apartemos un cupo prioritario para la próxima gira? ✨", 32],
      ["coleccionista", "siiii por favor", 30],
      ["lana", "Genial 👑 Te dejo en la lista prioritaria de Cali. Cuéntame tu idea para que los tatuadores la vayan preparando 🖤", 28],
    ],
  },
  {
    id: "c8",
    name: "Tom Becker",
    channel: "whatsapp",
    phone: "+49 151 2233 9087",
    city: "Berlín",
    lang: "de",
    stage: "calificando",
    idea: "Geometric blackwork",
    zona: "Wade (pantorrilla)",
    tags: ["tiene_idea", "idioma_de"],
    outcome: "seguimiento",
    hue: 200,
    msgs: [
      ["coleccionista", "Hallo, macht ihr geometrische blackwork tattoos?", 140],
      ["lana", "Hallo, schön dich zu lesen 🖤 Ja, geometrisches Blackwork ist eine unserer Spezialitäten. Welche Stelle und welche Größe stellst du dir vor? ✨", 139],
      ["coleccionista", "an der Wade, mittelgroß. Ich reise im August nach Bogotá", 137],
      ["lana", "Perfekt 👑 Lass uns eine kostenlose Beratung machen, um deine diseño único hecho para ti zu entwerfen und deine Sitzung im August zu sichern. Welche Woche passt dir? 🤍", 134],
    ],
  },
  {
    id: "c9",
    name: "Camilo Ardila",
    channel: "whatsapp",
    phone: "+57 312 778 4410",
    city: "Bogotá",
    stage: "perdido",
    idea: "Frase brazo",
    tags: ["indeciso", "reactivar"],
    outcome: "perdido",
    hue: 8,
    msgs: [
      ["coleccionista", "cuanto una frase pequeña en el brazo", 1440],
      ["lana", "Hola 🖤 Una frase fina luce muy elegante. El valor lo define un tatuador según tamaño y ubicación. ¿La quieres delgada tipo caligrafía? Cuéntame y te ayudo a aterrizarla ✨", 1439],
      ["coleccionista", "lo voy a pensar", 1438],
      ["lana", "Claro, tómate tu tiempo 🤍 Cuando quieras te aparto un cupo. Te dejo nuestro IG para que te inspires: @last_rules_tattoo 👑", 1437],
    ],
  },
  {
    id: "c10",
    name: "Daniela Pérez",
    channel: "instagram",
    handle: "@dani_perezz",
    city: "Bogotá",
    stage: "abono",
    idea: "Serpiente fine line",
    zona: "Columna",
    tamano: "~25 cm",
    tags: ["tiene_idea", "agendando", "abono_pendiente"],
    outcome: "agendado",
    hue: 300,
    msgs: [
      ["coleccionista", "quiero una serpiente por la columna, fine line", 110],
      ["lana", "Qué elegancia 🖤 La columna pide pulso de tatuador y queda espectacular en fine line. ¿La imaginas larga siguiendo la espalda? ✨", 109],
      ["coleccionista", "sí larga, unos 25 cm. cuando podría?", 106],
      ["lana", "Tengo cupos esta semana antes de que se llenen 👑 Para apartarlo va el abono de $100.000 (se descuenta del total). ¿Te paso los datos para asegurar tu fecha? 🖤", 104],
      ["coleccionista", "dale pásame los datos", 100],
      ["lana", "Listo ✨ Nequi/Daviplata 3227062595 a nombre de LAST RULES TATTOO. Apenas hagas el abono mándame el comprobante por aquí y queda confirmada tu tatuaje 🤍", 99],
    ],
  },
  {
    id: "c11",
    name: "Felipe Cano",
    channel: "facebook",
    city: "Bogotá",
    stage: "calificando",
    idea: "Cover up",
    zona: "Antebrazo",
    tags: ["cover_up", "tiene_idea"],
    outcome: "seguimiento",
    hue: 100,
    msgs: [
      ["coleccionista", "tengo un tatuaje viejo que quiero tapar, se puede?", 75],
      ["lana", "Claro que sí 🖤 Un cover bien hecho transforma por completo. los tatuadores son expertos en eso. ¿Me mandas una foto con buena luz del actual y me dices qué te gustaría encima? ✨", 74],
      ["coleccionista", "ya te la mando. quiero algo dark", 71],
      ["lana", "Perfecto, el dark work es ideal para cubrir 👑 Con la foto los tatuadores diseñan tu diseño único hecho para ti. ¿Agendamos una asesoría gratis para verlo en persona? 🤍", 69],
    ],
  },
  {
    id: "c12",
    name: "Isabella Ruiz",
    channel: "whatsapp",
    phone: "+57 318 990 3321",
    city: "Bogotá",
    stage: "nuevo",
    tags: ["menor", "validar_politica"],
    outcome: "seguimiento",
    hue: 340,
    msgs: [
      ["coleccionista", "hola tengo 16, me pueden tatuar?", 55],
      ["lana", "Gracias por preguntarlo 🖤 Para tatuar a un menor necesitamos el acompañamiento legal de tu acudiente (presente y con autorización). Si lo tienes, con gusto coordinamos con el director artístico ✨", 54],
      ["coleccionista", "ah ok, mi mamá puede ir conmigo", 52],
      ["lana", "Perfecto 👑 Con tu acudiente presente lo hacemos. Cuéntame tu idea y la vamos preparando para cuando agendemos 🤍", 50],
    ],
  },
  {
    id: "c13",
    name: "Stephanie Cruz",
    channel: "instagram",
    handle: "@step_cruz",
    city: "Bogotá",
    stage: "calificando",
    idea: "Micro-realismo ojo",
    zona: "Brazo",
    tags: ["tiene_idea", "duda_dolor"],
    outcome: "seguimiento",
    hue: 260,
    msgs: [
      ["coleccionista", "quiero un ojo en microrealismo pero me da miedo el dolor 😬", 88],
      ["lana", "Te entiendo 🤍 Te soy honesta: se siente, pero en el brazo es de las zonas más llevables y los tatuadores manejan el ritmo con pausas. El microrealismo ahí queda impecable 🖤 ¿Lo quieres pequeño y discreto o con más detalle? ✨", 87],
      ["coleccionista", "pequeño y discreto", 85],
      ["lana", "Perfecto para una primera tatuaje 👑 Te propongo una asesoría gratis para definir tamaño exacto y que conozcas el estudio. ¿Esta semana te sirve? 🖤", 83],
    ],
  },
  {
    id: "c14",
    name: "Óscar Méndez",
    channel: "whatsapp",
    phone: "+57 310 445 2200",
    city: "Bogotá",
    stage: "nuevo",
    tags: ["reclamo", "escalar"],
    outcome: "seguimiento",
    hue: 0,
    msgs: [
      ["coleccionista", "oigan no me gustó como me quedó la pieza que me hicieron", 40],
      ["lana", "Lamento mucho que no estés satisfecho con el resultado de tu tatuaje 🖤 Quiero que quedes feliz. Te conecto con el director artístico, quien te escribirá en breve para revisarlo personalmente 🤍", 39],
    ],
  },
  {
    id: "c15",
    name: "ana.lucia",
    channel: "instagram",
    handle: "@ana.lucia.g",
    city: "Bogotá",
    stage: "cotizado",
    idea: "Mandala hombro",
    zona: "Hombro",
    tamano: "~18 cm",
    tags: ["tiene_idea", "cotizado"],
    outcome: "agendado",
    hue: 190,
    msgs: [
      ["coleccionista", "me encantó un mandala que vi en su feed, quiero algo así en el hombro", 130],
      ["lana", "¡Qué buen ojo! 🖤 El mandala fluye precioso en el hombro. Recuerda que creamos uno único tuyo, no una copia. ¿De qué tamaño lo imaginas? ✨", 129],
      ["coleccionista", "mediano, que baje un poco al brazo", 127],
      ["lana", "Hermoso 👑 los tatuadores lo cotizaron y es una tatuaje de una sesión. Para apartar tu cupo va el abono de $100.000 que se descuenta. ¿Agendamos para este fin de semana? 🤍", 96],
      ["coleccionista", "siii", 92],
    ],
  },
  {
    id: "c16",
    name: "Nicolás Vega",
    channel: "whatsapp",
    phone: "+57 319 660 1180",
    city: "Bogotá",
    stage: "calificando",
    idea: "Lettering antebrazo",
    zona: "Antebrazo interno",
    tags: ["tiene_idea", "primera_vez"],
    outcome: "seguimiento",
    hue: 220,
    msgs: [
      ["coleccionista", "seria mi primer tatuaje, un lettering en el antebrazo", 64],
      ["lana", "Qué emoción tu primera tatuaje 🖤 El lettering en el antebrazo interno luce con mucha personalidad. ¿Ya tienes la frase y un estilo de letra en mente? ✨", 63],
      ["coleccionista", "si tengo la frase, algo tipo manuscrito", 61],
      ["lana", "Manuscrito fino queda elegante y atemporal 👑 los tatuadores lo trazan a mano alzada para que sea único. ¿Agendamos una asesoría gratis para definir la composición? 🤍", 59],
    ],
  },
];

export const SEED_CONVERSATIONS: Conversation[] = seeds.map((s) => {
  const messages = thread(s.msgs);
  const lastAt = messages.length ? messages[messages.length - 1].at : mins(0);
  return {
    id: s.id,
    contact: {
      id: `k_${s.id}`,
      name: s.name,
      handle: s.handle,
      phone: s.phone,
      channel: s.channel,
      city: s.city,
      lang: s.lang ?? "es",
      avatarHue: s.hue,
    },
    channel: s.channel,
    stage: s.stage,
    messages,
    tags: s.tags,
    idea: s.idea,
    zona: s.zona,
    tamano: s.tamano,
    lastAt,
    unread: messages[messages.length - 1]?.sender === "coleccionista",
    outcome: s.outcome ?? null,
  };
});
